In [21]:
import pandas as pd
import numpy as np

In [30]:
#Read CSV for Danny Green 

green_df = pd.read_csv("danny green stats .csv")

# delete unwanted colums

green_df = green_df.drop (columns=[
    'FT', 'FTA', 'FT%', 'ORB','DRB', 'TRB', 'AST', 'STL', 
    'BLK', 'TOV', 'PF', 'PTS', 'GmSc', '+/-','MP', 'FG','FGA','FG%', 'Tm', 'Rk', 'G'])

# headings
green_df = green_df.rename(columns={"Unnamed: 5":"Home vs Away","Unnamed: 7":"Win/Loss by:"})
green_df['Home vs Away'].fillna("Home", inplace = True)
green_df['Home vs Away'] = green_df['Home vs Away'].replace(to_replace = "@", value = "Away")
# STEP 5 - Add Player 
green_df['Name'] = "Danny Green"

green_mean = green_df['3P'].mean()
green_3_percentage = green_df['3P'] / green_df['3PA'] * 100
print(f" Danny Green on average, makes {round(green_mean,2)} 3 pointers per game")
print(f" Danny Green's 3 point percentage is {green_3_percentage.mean()}")

 Danny Green on average, makes 2.26 3 pointers per game
 Danny Green's 3 point percentage is 39.55845664583529

,Date,Age,Home vs Away,Opp,Win/Loss by:,GS,3P,3PA,3P%,Name
0,2018-10-17,31-117,Home,CLE,W (+12),1,3,7,0.429,Danny Green
1,2018-10-19,31-119,Home,BOS,W (+12),1,4,7,0.571,Danny Green
2,2018-10-20,31-120,Away,WAS,W (+4),1,1,8,0.125,Danny Green
3,2018-10-22,31-122,Home,CHO,W (+21),1,4,6,0.667,Danny Green
4,2018-10-24,31-124,Home,MIN,W (+7),1,2,5,0.4,Danny Green
...,...,...,...,...,...,...,...,...,...,...
75,2019-03-28,31-279,Away,NYK,W (+25),1,5,8,0.625,Danny Green
76,2019-03-30,31-281,Away,CHI,W (+23),1,2,2,1,Danny Green
77,2019-04-01,31-283,Home,ORL,W (+12),1,7,10,0.7,Danny Green
78,2019-04-03,31-285,Away,BRK,W (+10),1,0,4,0,Danny Green
79,2019-04-05,31-287,Away,CHO,L (-2),1,2,3,0.667,Danny Green

In [32]:
#Read CSV for Kawai Lenord
leonard_df = pd.read_csv("kawai Lenord stats.csv")

leonard_df = leonard_df.drop (columns=[
    'FT', 'FTA', 'FT%', 'ORB','DRB', 'TRB', 'AST', 'STL', 
    'BLK', 'TOV', 'PF', 'PTS', 'GmSc', '+/-','MP', 'FG','FGA','FG%', 'Tm', 'Rk', 'G'])

#  Add Player 
leonard_df['Name'] = "Kawai Leonard"
leonard_df = leonard_df.rename(columns={"Unnamed: 5":"Home vs Away","Unnamed: 7":"Win/Loss by:"})
leonard_df['Home vs Away'].fillna("Home", inplace = True)
leonard_df['Home vs Away'] = leonard_df['Home vs Away'].replace(to_replace = "@", value = "Away")
# headings
leonard_df = leonard_df.rename(columns={" ":"Home vs Away"," .1":"Win/Loss by:"})


leonard_mean = leonard_df['3P'].mean()
leonard_3_percentage = leonard_df['3P'] / leonard_df['3PA'] * 100
print(f" Kawhi Leonard on average, makes {round(leonard_mean,2)} 3 pointers per game")
print(f" Kawhi Leonard's 3 point percentage is {leonard_3_percentage.mean()}")

 Kawhi Leonard on average, makes 1.99 3 pointers per game
 Kawhi Leonard's 3 point percentage is 34.509637188208615

In [34]:
#Read CSV for Marc Gasol

gasol_df = pd.read_csv("marc Gasol stats.csv")



gasol_df = gasol_df.drop (columns=[
    'FT', 'FTA', 'FT%', 'ORB','DRB', 'TRB', 'AST', 'STL', 
    'BLK', 'TOV', 'PF', 'PTS', 'GmSc', '+/-','MP', 'FG','FGA','FG%', 'Tm', 'Rk'])
gasol_df['Name'] = "Kawai Leonard"
gasol_df = gasol_df.rename(columns={"Unnamed: 5":"Home vs Away","Unnamed: 7":"Win/Loss by:"})
gasol_df['Home vs Away'].fillna("Home", inplace = True)
gasol_df['Home vs Away'] = gasol_df['Home vs Away'].replace(to_replace = "@", value = "Away")

#Player name 

gasol_df['Name'] = "Marc Gasol"


gasol_mean = gasol_df['3P'].mean()
gasol_3_percentage = gasol_df['3P'] / gasol_df['3PA'] * 100
print(f" Marc Gasol on average, makes {round(gasol_mean,2)} 3 pointers per game")
print(f" Marc Gasol's 3 point percentage is {gasol_3_percentage.mean()}")

 Marc Gasol on average, makes 1.28 3 pointers per game
 Marc Gasol's 3 point percentage is 36.81639666175748